require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe HolesController do

  def mock_hole(stubs={})
    @mock_hole ||= mock_model(Hole, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all holes as @holes" do
      Hole.stub(:all) { [mock_hole] }
      get :index
      assigns(:holes).should eq([mock_hole])
    end
  end

  describe "GET show" do
    it "assigns the requested hole as @hole" do
      Hole.stub(:find).with("37") { mock_hole }
      get :show, :id => "37"
      assigns(:hole).should be(mock_hole)
    end
  end

  describe "GET new" do
    it "assigns a new hole as @hole" do
      Hole.stub(:new) { mock_hole }
      get :new
      assigns(:hole).should be(mock_hole)
    end
  end

  describe "GET edit" do
    it "assigns the requested hole as @hole" do
      Hole.stub(:find).with("37") { mock_hole }
      get :edit, :id => "37"
      assigns(:hole).should be(mock_hole)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created hole as @hole" do
        Hole.stub(:new).with({'these' => 'params'}) { mock_hole(:save => true) }
        post :create, :hole => {'these' => 'params'}
        assigns(:hole).should be(mock_hole)
      end

      it "redirects to the created hole" do
        Hole.stub(:new) { mock_hole(:save => true) }
        post :create, :hole => {}
        response.should redirect_to(hole_url(mock_hole))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved hole as @hole" do
        Hole.stub(:new).with({'these' => 'params'}) { mock_hole(:save => false) }
        post :create, :hole => {'these' => 'params'}
        assigns(:hole).should be(mock_hole)
      end

      it "re-renders the 'new' template" do
        Hole.stub(:new) { mock_hole(:save => false) }
        post :create, :hole => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested hole" do
        Hole.stub(:find).with("37") { mock_hole }
        mock_hole.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :hole => {'these' => 'params'}
      end

      it "assigns the requested hole as @hole" do
        Hole.stub(:find) { mock_hole(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:hole).should be(mock_hole)
      end

      it "redirects to the hole" do
        Hole.stub(:find) { mock_hole(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(hole_url(mock_hole))
      end
    end

    describe "with invalid params" do
      it "assigns the hole as @hole" do
        Hole.stub(:find) { mock_hole(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:hole).should be(mock_hole)
      end

      it "re-renders the 'edit' template" do
        Hole.stub(:find) { mock_hole(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested hole" do
      Hole.stub(:find).with("37") { mock_hole }
      mock_hole.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the holes list" do
      Hole.stub(:find) { mock_hole }
      delete :destroy, :id => "1"
      response.should redirect_to(holes_url)
    end
  end

end
